### ISSUE TITLE
HPD: We should be able to split the swap usage for each schain 

### ISSUE THREAD

**Issue by EvgeniyZZ** [skalenetwork/skale-admin#1027] opened 2023-12-11 18:42 UTC
**Description**
Right now we don't have limits or priority for swap usage, as result one schain can use all allocated swap. 
We should introduce limits for swap for each schain, depends on amount on the node 
@kladkogex  @DmytroNazarenko  add more context

**Comment by dmytrotkk** [comment] 2024-05-10 12:45
Swap memory is already limited by default if memory for the container is limited. 
For each sChain container we're allocating 2.6GB RAM on the machine, which means that additional 2.6GB will be allocated.

From docker docs:

> --memory="300m" and --memory-swap is not set, the container can use 600m in total of memory and swap.

See more details here: https://docs.docker.com/config/containers/resource_constraints/#--memory-swap-details

Example of correct setup on the node:
```bash
docker inspect skale_schain_test | grep Memory
            "Memory": 2678032302,
            "MemoryReservation": 0,
            "MemorySwap": 5356064604,
            "MemorySwappiness": null,
```

Meaning that `2678032302` bytes of RAM are allocated and the total for memory + swap is `5356064604`.

Issue that we had caused by disabled swap limit capability in the kernel. You can run this command to check:

```bash
docker info
```

This line in the end means that the swap limiting capability is disabled:
```
WARNING: No swap limit support
```

To enable it do the following:

1) Log into the Ubuntu or Debian host as a user with sudo privileges.

2) Edit the `/etc/default/grub` file. Add or edit the `GRUB_CMDLINE_LINUX` line to add the following two key-value pairs:

```
GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"
```

3) Update GRUB.

```
sudo update-grub
```

4) Reboot the machine 

More details here: https://unix.stackexchange.com/questions/342735/docker-warning-no-swap-limit-support

Issue can be fixed without code changes on our side.

**Comment by PolinaKiporenko** [comment] 2024-05-20 12:14
2.7.0-beta.0

**Closed as completed** 2024-05-20 12:14 UTC
Labels: enhancement, epic:HPD

**Comment by OleksanderSalamatov** [comment] 2024-07-03 12:18
Verified

admin: 2.7.0-beta.2

Swap limit turned on in grub
After skaled swap usage exceeded ~2.6Gb skaled container was killed, and admin successfully restarted it 
![image](https://github.com/skalenetwork/skale-admin/assets/84843611/91c3d5eb-dae8-44f7-841c-c0ed93008df8)

```
[2024-07-03 11:52:46,599 INFO][12][numb-heavy-sadalachbia][T_1] - tools.notifications.messages:130 - Sending checks notification with state [('blocks', False), ('exit_code_ok', True), ('firewall_rules', True), ('ima_container', True), ('process', True), ('rpc', False), ('skaled_container', False), ('volume', True)]
[2024-07-03 11:52:46,600 INFO][12][numb-heavy-sadalachbia][T_1] - tools.notifications.messages:135 - Saving new checks state 1 [('blocks', False), ('exit_code_ok', True), ('firewall_rules', True), ('ima_container', True), ('process', True), ('rpc', False), ('skaled_container', False), ('volume', True)]
[2024-07-03 11:52:46,600 INFO][12][numb-heavy-sadalachbia][T_1] - core.schains.monitor.main:168 - Skaled status: {'blocks': False, 'config': True, 'config_updated': False, 'exit_code_ok': True, 'exit_zero': False, 'firewall_rules': True, 'ima_container': True, 'process': True, 'rotation_id_updated': True, 'rpc': False, 'skaled_container': False, 'upstream_exists': True, 'volume': True}
[2024-07-03 11:52:46,601 INFO][12][numb-heavy-sadalachbia][T_1] - core.schains.monitor.main:170 - Upstream config /skale_node_data/schains/numb-heavy-sadalachbia/schain_numb-heavy-sadalachbia_3_1718969659.json
[2024-07-03 11:52:46,601 INFO][12][numb-heavy-sadalachbia][T_1] - core.schains.monitor.skaled_monitor:305 - Choosing skaled monitor
[2024-07-03 11:52:46,601 INFO][12][numb-heavy-sadalachbia][T_1] - core.schains.skaled_status:99 - skaled status file: 
[2024-07-03 11:52:46,602 INFO][12][numb-heavy-sadalachbia][T_1] - core.schains.ssl:66 - ssl_files_change_date: 2024-05-14 14:45:21.287731, ssl_change_date for chain numb-heavy-sadalachbia: 2024-05-14 14:45:21.287731
[2024-07-03 11:52:46,608 INFO][12][numb-heavy-sadalachbia][T_1] - core.schains.monitor.skaled_monitor:55 - Skaled monitor type starting RegularSkaledMonitor
[2024-07-03 11:52:46,609 INFO][12][numb-heavy-sadalachbia][T_1] - web.models.schain:155 - Changing monitor_last_seen for numb-heavy-sadalachbia to 2024-07-03 11:52:46.609490
[2024-07-03 11:52:46,820 INFO][12][numb-heavy-sadalachbia][T_1] - core.schains.firewall.rule_controller:192 - Rules status: missing rules 0, redundant rules: 0
[2024-07-03 11:52:47,465 INFO][12][numb-heavy-sadalachbia][T_1] - core.schains.monitor.containers:100 - sChain numb-heavy-sadalachbia: restarting container
[2024-07-03 11:52:47,466 INFO][12][numb-heavy-sadalachbia][T_1] - core.schains.runner:172 - 
[2024-07-03 11:52:47,466 INFO][12][numb-heavy-sadalachbia][T_1] - tools.docker_utils:339 - Restarting container: skale_schain_numb-heavy-sadalachbia
[2024-07-03 11:52:48,670 INFO][12][numb-heavy-sadalachbia][T_1] - tools.docker_utils:343 - Container restarted: skale_schain_numb-heavy-sadalachbia
[2024-07-03 11:52:48,670 INFO][12][numb-heavy-sadalachbia][T_1] - web.models.schain:170 - Changing restart count for numb-heavy-sadalachbia to 1
[2024-07-03 11:52:48,674 INFO][12][numb-heavy-sadalachbia][T_1] - web.models.schain:175 - Changing failed rpc count for numb-heavy-sadalachbia to 0

```

**Comment by OleksanderSalamatov** [comment] 2024-07-31 18:49
Also we can check if swap limit is applied in watchdog (ip:3009/status/core)

Before enabling:
```
            "swap_limit": -1,
```

After enabling:
```
            "swap_limit": 1339016642,
```

**Comment by alexgex** [comment] 2024-09-04 13:08
Here's the actual data on swap limit details collected from SKALE nodes:

https://docs.google.com/spreadsheets/d/1u_TcxQ7GN8aOwwkCwiOnvlir9n7HPNJTVJTI1QD-BaM/edit?usp=sharing
