### ISSUE TITLE
Skale admin generate accounts balances for actual node group after node rotation

### ISSUE THREAD

**Issue by oleksandrSydorenkoJ** [skalenetwork/skale-admin#930] opened 2023-03-13 11:04 UTC
**Versions:**
skalenetwork/admin:2.11.0-sync-node.1

**Preconditions:**
Network: Regression
Skale chain name: curly-red-alterf - medium type, gen 2, rotationID = 8 

**To Reproduce**
1. Create schain any generation
2. Send IMA transactions - M2S and S2M (save NodeID for the sender)
3. Run node exit on the node-sender
4. connect archive node for the schain
5. check block with IMA-transfer from  archive node and for core nodes
6. check the  balance for the rotated node on the archive node and the core node

  
**Expected behavior**
Archive node should be able to catchup blocks with the same state as on core nodes. 
Balances of nodes should be the same for core and archive nodes from 0 block.

**Actual state:**
Skale admin generate 0 block with balances of the latest node group and ignore rotated nodes balance.

**Logs**:
Archive node:
```
Active nodeId 7:
> eth.getBalance('0xE273448352FDafE03a2174ECEC0F6FDE548e24FA')  
9.99999999999999632294e+29

Left nodeId 5
> eth.getBalance('0x385b24207f4b305c2efa112c456adf9db064ea5e')
0
```

Core node:
```
Active nodeId 7:
> eth.getBalance('0xE273448352FDafE03a2174ECEC0F6FDE548e24FA')
999987735000000000

Left nodeId 5
> eth.getBalance('0x385b24207f4b305c2efa112c456adf9db064ea5e')
9.99999999999999768315e+29


```

**Comment by DmytroNazarenko** [comment] 2023-04-14 15:44
Should be fixed by https://github.com/skalenetwork/skaled/issues/1450

**Comment by DmytroNazarenko** [comment] 2023-06-12 12:58
https://github.com/skalenetwork/skaled/issues/1450 fixes issue only for new chains, for old chains - https://github.com/skalenetwork/skaled/issues/1450 should fix

**Comment by DmytroNazarenko** [comment] 2023-06-16 12:17
Closed as a duplicate of https://github.com/skalenetwork/skaled/issues/1450

**Closed as completed by DmytroNazarenko** 2023-06-16 12:17 UTC
Labels: bug, epic:node-rotation, epic:archive-node
